### ISSUE TITLE
Questions about how to determine ALGs

### ISSUE THREAD

**Issue by Mia1349** [conchoecia/odp#36]
Hi darrin,

Thank you for making some improvments to the software, I do think that add some formats check is necessary, there was one time I did not find out the chrom file was misformated, and I constantly get the error of database building failture, it took me a while to find out the bug...

Recently I want to use odp to plot the synteny of a group of fungi I am working on. But the build in ALGs databases were all from Metazoa, use them to color the synteny of fungi is just, does not make any sense, I think? so I thought I should get the ALGs myself from a set of fungi genomes, and maybe I could use them to color the synteny plots? is that how it works? I tried the first step but I am not sure where to go on from here.

This is the same test dataset I used to generate the ribbon plot. I already got the results from the **odp_nway_rbh** script, and this is the config.yaml I used. 
```
# this file is called config.yaml

# the number of species you want to be included in each analysis
nways: 5
# How you want to identify the orthologs [diamond|blastp]
search_method: diamond
num_permutations: 1000000
# What analyses you want to produce. Saves on some compute.
#  Must match headers of `xaxisspecies`. Order doesn't matter.
analyses:
  - ["TCS", "SCO", "PMA", "BFL"]
  - ["SCO", "PMA", "BFL", "RHO"]
  # - ["Homosapiens", "Dmel", "Mmus"]   # You can comment out lines if you would like
  
species:
  TCS:
    proteins: /home/liuhy/Source_Data/chequ/odp/TC/TCS_prots.pep
    chrom: /home/liuhy/Source_Data/chequ/odp/TC/TC.chrom
    genome: /home/liuhy/Source_Data/chequ/odp/TC/TC.fna
    minscafsize: 1000000
  SCO:
    proteins: /home/liuhy/Source_Data/chequ/odp/yicheng/Sco.pep 
    chrom: /home/liuhy/Source_Data/chequ/odp/yicheng/Sco.chrom3
    genome: /home/liuhy/Source_Data/chequ/odp/yicheng/Sco.fna
    minscafsize: 1000000
  PMA:
    proteins: /home/liuhy/Source_Data/chequ/odp/pecten_maximus/PMA.pep 
    chrom: /home/liuhy/Source_Data/chequ/odp/pecten_maximus/PMA.chrom
    genome: /home/liuhy/Source_Data/chequ/odp/pecten_maximus/PMA.fasta
    minscafsize: 1000000
  BFL:
    proteins: /home/liuhy/Source_Data/chequ/odp/branchiostoma/BFL.pep
    chrom: /home/liuhy/Source_Data/chequ/odp/branchiostoma/BFL.chrom
    genome: /home/liuhy/Source_Data/chequ/odp/branchiostoma/BFL.fasta
    minscafsize: 1000000
  RHO:
    proteins: /home/liuhy/Source_Data/chequ/odp/rhopilema_li/rhopilema_chromosome_v1.pep  
    chrom: /home/liuhy/Source_Data/chequ/odp/rhopilema_li/rhopilema_chromosome_v1.chrom
    genome: /home/liuhy/Source_Data/chequ/odp/rhopilema_li/rhopilema_chromosome_v1.fasta
    minscafsize: 1000000
```
I got the resulting folders(step1-step3), which files should be used for subsequent analysis? 

Mia
