### ISSUE TITLE
Error in rule plot_synteny_nocolor

### ISSUE THREAD

**Issue by HX-FAshur** [conchoecia/odp#74]
As the title says, I'm getting an error in rule plot_synteny_nocolor with the following config:

```
ignore_autobreaks: True       # Skip steps to find breaks in synteny blocks
diamond_or_blastp: "diamond"  # "diamond" or "blastp"
duplicate_proteins: "pass"    # currently only "fail" or "best". Fail doesn't allow duplicate names or seqs
plot_LGs: False                # Plot the ALGs based on the installed databases
plot_sp_sp: True              # Plot the synteny between two species, if False just generates .rbh files

species:
  CutaneotrichosporonspHIS471:
    proteins: odp/files/CutaneotrichosporonspHIS471MT.faa
    chrom: odp/files/CutaneotrichosporonspHIS471MT.chrom
    genome: odp/files/CutaneotrichosporonspHIS471MT.fasta
  CutaneotrichosporonCavernicolaHIS641:
    proteins: odp/files/CutaneotrichosporonCavernicolaHIS641MT.faa
    chrom: odp/files/CutaneotrichosporonCavernicolaHIS641MT.chrom
    genome: odp/files/CutaneotrichosporonCavernicolaHIS641MT.fasta
```

Below, you can see the complete error message. Also, I've attached the complete log as well as the input files (as .txt's) for the failing job:

- odp/step1-rbh/CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471_reciprocal_best_hits.D.FET.rbh
- odp/step0-chromsize/analyses/CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471.chromsize

### Terminal output
![image](https://github.com/conchoecia/odp/assets/49619096/fb001aa7-364c-4230-8d25-1c7f13c5c7d1)
[2024-05-19T190337.595789.snakemake.log](https://github.com/conchoecia/odp/files/15377222/2024-05-19T190337.595789.snakemake.log)
### Files
[CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471_reciprocal_best_hits.D.FET.rbh.txt](https://github.com/conchoecia/odp/files/15377284/CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471_reciprocal_best_hits.D.FET.rbh.txt)
[CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471.chromsize](https://github.com/conchoecia/odp/files/15377292/CutaneotrichosporonCavernicolaHIS641_CutaneotrichosporonspHIS471.chromsize)
